Fix navbar, small refactor

diff --git a/test/pal-actions.yml b/test/pal-actions.yml
--- a/test/pal-actions.yml
+++ b/test/pal-actions.yml
@@ -1,62 +1,61 @@
 test:
-  - # Test Auth, input query parameter and script
-    # curl -sk -H 'X-Pal-Auth: PaLLy!@#890-' 'https://127.0.0.1:8443/v1/pal/run/test/auth?input=helloworld'
-    action: auth
+  # curl -sk -H 'X-Pal-Auth: PaLLy!@#890-' 'https://127.0.0.1:8443/v1/pal/run/test/auth?input=helloworld'
+  - action: auth
+    desc: Test auth_header Restriction
     auth_header: X-Pal-Auth PaLLy!@#890-
     output: true
     concurrent: true
-    cmd: |
-      echo $INPUT
+    cmd: echo "$INPUT auth"
 
-  - # Test unauthorized
-    # curl -sk -H 'X-Pal-Auth: PaLLy!@#890-' 'https://127.0.0.1:8443/v1/pal/run/test/unauth'
-    action: unauth
-    auth_header: X-Pal-Auth PaLLy!@#890-
+  # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/no_auth'
+  - action: no_auth
+    desc: Test No auth_header and schedule
+    auth_header:
     output: true
     schedule: "* * * * *"
     concurrent: true
-    cmd: echo helloworld
+    cmd: echo "$INPUT no_auth"
 
-  - # Test fail cmd notification
-    # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/fail'
-    action: fail
+  # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/fail'
+  - action: fail
+    desc: Test Failing Action
     concurrent: true
     output: true
-    input_validate: required
     on_error:
       notification: "test/fail failed test"
-    cmd: echo $INPUT && exit 1
+    cmd: echo "$INPUT fail" && exit 1
 
-  - # Test blocking
-    # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/block'
-    action: block
+  # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/block'
+  - action: block
+    desc: Test Concurrent False, Blocking Action
     concurrent: false
     output: true
-    cmd: sleep $INPUT || sleep 10; echo "block"
+    cmd: sleep $INPUT || sleep 10; echo "$INPUT block"
 
-  - # Test no blocking
-    # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/noblock'
-    action: noblock
+  # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/no_block'
+  - action: no_block
+    desc: Test Concurrent True, No Blocking Action"
     concurrent: true
     output: true
-    cmd: echo "noblock"
+    cmd: echo "$INPUT no_block"
 
-  - # Test no output
-    # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/norc'
-    action: norc
+  # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/no_output'
+  - action: no_output
+    desc: Test Hidden Output and No Last Output
+    output: false
     concurrent: true
-    cmd: echo
+    cmd: echo "$INPUT no_output"
 
-  - # Test background output
-    # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/background'
-    action: background
+  # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/background'
+  - action: background
+    desc: Test Running Action In Background
     background: true
     concurrent: true
-    cmd: echo "background"
+    cmd: echo "$INPUT background"
 
-  - # Test background output
-    # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/background_fail'
-    action: background_fail
+  # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/background_fail'
+  - action: background_fail
+    desc: Test Background Action Failure
     background: true
     concurrent: true
     response_headers:
@@ -64,13 +63,20 @@ test:
         value: "*"
       - header: X-Pal
         value: Test
-    cmd: echo "background_fail" && exit 1
+    cmd: echo "$INPUT background_fail" && exit 1
+
+  # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/input_validate'
+  - action: input_validate
+    output: true
+    concurrent: true
+    input_validate: required,gte=1
+    cmd: echo "$INPUT input_validate"
 
 json:
-  - # Test json data
-    # curl -sk -XPOST -d '{"hello":"world"}' 'https://127.0.0.1:8443/v1/pal/run/json/newres'
-    # curl -sk 'https://127.0.0.1:8443/v1/pal/run/json/newres?input=%7B%22hello%22%3A%22world%22%7D'
-    action: newres
+  # curl -sk -XPOST -d '{"hello":"world"}' 'https://127.0.0.1:8443/v1/pal/run/json/parse'
+  # curl -sk 'https://127.0.0.1:8443/v1/pal/run/json/parse?input=%7B%22hello%22%3A%22world%22%7D'
+  - action: parse
+    desc: Run jq On Input JSON
     output: true
     concurrent: true
     response_headers:
@@ -78,14 +84,13 @@ json:
         value: application/json
     # input_validate: required,json
     on_error:
-      notification: "Failed JSON Validation"
+      notification: "json/parse: error failed parsing JSON"
     cmd: echo "$INPUT" | jq
 
-test2:
-  - # Test content type
-    # curl -sk -o /dev/null -w '%{content_type}' 'https://127.0.0.1:8443/v1/pal/run/test2/contenttype'
-    action: contenttype
-    desc: Sets cache time and render of basic hello world HTML site
+html:
+  # curl -sk -o /dev/null -w '%{content_type}' 'https://127.0.0.1:8443/v1/pal/run/html/index_cache'
+  - action: index_cache
+    desc: Sets Max-Age Cache Control & Renders HTML Content-Type
     output: true
     concurrent: true
     response_headers:
@@ -93,4 +98,5 @@ test2:
         value: max-age=3600
       - header: Content-Type
         value: text/html
-    cmd: echo '<!DOCTYPE html><html><head><title>Hello, World!</title></head><body><h1>Hello, World!</h1></body></html>'
+    cmd: |
+      echo "<!DOCTYPE html><html><head><title>Hello, World!</title></head><body><h1>$INPUT Hello, World!</h1></body></html>"
