Change UI layout and template handling, make values more human readable in UI

diff --git a/test/pal-actions.yml b/test/pal-actions.yml
--- a/test/pal-actions.yml
+++ b/test/pal-actions.yml
@@ -8,7 +8,7 @@ test:
     tags:
       - restricted
       - test
-    cmd: echo "$INPUT auth"
+    cmd: echo "$PAL_GROUP $PAL_ACTION $PAL_UPLOAD_DIR $PWD $PAL_INPUT auth"
 
   # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/no_auth'
   - action: no_auth
@@ -17,7 +17,16 @@ test:
     output: true
     cron: "* * * * *"
     concurrent: true
-    cmd: echo "$INPUT no_auth"
+    cmd: echo "$PAL_INPUT no_auth"
+
+    # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/sunday_test'
+  - action: sunday_test
+    desc: Test cron at 5 on Sunday
+    auth_header:
+    output: true
+    cron: "0 5 * * 0"
+    concurrent: true
+    cmd: echo "$PAL_INPUT sunday_test"
 
   # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/fail'
   - action: fail
@@ -26,14 +35,14 @@ test:
     output: true
     on_error:
       notification: "test/fail failed test"
-    cmd: echo "$INPUT fail" && exit 1
+    cmd: echo "$PAL_INPUT fail" && exit 1
 
   # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/block'
   - action: block
     desc: Test Concurrent False, Blocking Action
     concurrent: false
     output: true
-    cmd: sleep $INPUT || sleep 10; echo "$INPUT block"
+    cmd: sleep $PAL_INPUT || sleep 10; echo "$PAL_INPUT block"
 
   # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/fail_timeout'
   - action: fail_timeout
@@ -41,28 +50,28 @@ test:
     concurrent: false
     output: true
     timeout: 2
-    cmd: sleep $INPUT || sleep 10; echo "$INPUT fail_timeout"
+    cmd: sleep $PAL_INPUT || sleep 10; echo "$PAL_INPUT fail_timeout"
 
   # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/no_block'
   - action: no_block
     desc: Test Concurrent True, No Blocking Action"
     concurrent: true
     output: true
-    cmd: echo "$INPUT no_block"
+    cmd: echo "$PAL_INPUT no_block"
 
   # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/no_output'
   - action: no_output
     desc: Test Hidden Output and No Last Output
     output: false
     concurrent: true
-    cmd: echo "$INPUT no_output"
+    cmd: echo "$PAL_INPUT no_output"
 
   # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/background'
   - action: background
     desc: Test Running Action In Background
     background: true
     concurrent: true
-    cmd: echo "$INPUT background"
+    cmd: echo "$PAL_INPUT background"
 
   # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/background_fail'
   - action: background_fail
@@ -74,7 +83,7 @@ test:
         value: "*"
       - header: X-Pal
         value: Test
-    cmd: echo "$INPUT background_fail" && exit 1
+    cmd: echo "$PAL_INPUT background_fail" && exit 1
 
   # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/input_validate'
   - action: input_validate
@@ -83,7 +92,7 @@ test:
     input_validate: required,gte=2
     tags:
       - validate
-    cmd: echo "$INPUT input_validate"
+    cmd: echo "$PAL_INPUT input_validate"
 
   # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/retry_fail'
   - action: retry_fail
@@ -93,7 +102,7 @@ test:
     on_error:
       retries: 2
       retry_interval: 10
-    cmd: echo "$INPUT retry fail" && exit 1
+    cmd: echo "$PAL_INPUT retry fail" && exit 1
 
 json:
   # curl -sk -XPOST -d '{"hello":"world"}' 'https://127.0.0.1:8443/v1/pal/run/json/parse'
@@ -110,7 +119,20 @@ json:
       - json
     on_error:
       notification: "json/parse: error failed parsing JSON"
-    cmd: echo "$INPUT" | jq
+    cmd: echo "$PAL_INPUT" | jq
+  # curl -sk -XPOST -H 'X-PAL-TEST: true' -d 'test_body' 'https://127.0.0.1:8443/v1/pal/run/json/parse_pal_request?test=true'
+  - action: parse_pal_request
+    desc: Run jq On PAL_REQUEST JSON
+    output: true
+    concurrent: true
+    resp_headers:
+      - header: Content-Type
+        value: application/json
+    tags:
+      - json
+    on_error:
+      notification: "json/parse_pal_request: error failed parsing PAL_REQUEST"
+    cmd: echo "$PAL_REQUEST" | jq
 
 html:
   # curl -sk -o /dev/null -w '%{content_type}' 'https://127.0.0.1:8443/v1/pal/run/html/index_cache'
@@ -126,4 +148,4 @@ html:
     tags:
       - html
     cmd: |
-      echo "<!DOCTYPE html><html><head><title>Hello, World!</title></head><body><h1>$INPUT Hello, World!</h1></body></html>"
+      echo "<!DOCTYPE html><html><head><title>Hello, World!</title></head><body><h1>$PAL_INPUT Hello, World!</h1></body></html>"
