Expand on_error on_success and change last duration to readable output

diff --git a/test/test.yml b/test/test.yml
--- a/test/test.yml
+++ b/test/test.yml
@@ -17,6 +17,9 @@ test:
     tags:
       - restricted
       - test
+    on_success:
+      run: test/echo_success
+      input: $PAL_OUTPUT
     cmd: echo "$PAL_GROUP $PAL_ACTION $PAL_UPLOAD_DIR $PWD $PAL_INPUT auth"
 
   # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/no_auth'
@@ -48,6 +51,8 @@ test:
     output: true
     on_error:
       notification: "group=$PAL_GROUP action=$PAL_ACTION input=$PAL_INPUT output=$PAL_OUTPUT"
+      run: test/echo_failure
+      input: $PAL_OUTPUT
     cmd: echo "$PAL_INPUT fail" && exit 1
 
   # curl -sk 'https://127.0.0.1:8443/v1/pal/run/test/block'
@@ -140,3 +145,23 @@ test:
     on_error:
       notification: "$PAL_GROUP/$PAL_ACTION: error failed running container: $PAL_OUTPUT: input $PAL_INPUT"
     cmd: echo "$PAL_INPUT container_run"
+
+  - action: echo_failure
+    desc: Show output from failed jobs
+    auth_header: X-Pal-Auth PaLLy!@#890-
+    output: true
+    on_success:
+      notification: "$PAL_GROUP/$PAL_ACTION error input=$PAL_INPUT"
+    cmd: echo "$PAL_INPUT echo_failure"
+
+  - action: echo_success
+    desc: Show output from success jobs
+    auth_header: X-Pal-Auth PaLLy!@#890-
+    output: true
+    cmd: echo "$PAL_INPUT echo_success"
+
+  - action: success_error
+    desc: Error or Success action with exit status
+    auth_header: X-Pal-Auth PaLLy!@#890-
+    output: true
+    cmd: sleep 5 && exit $PAL_INPUT
